baseURL = "/"
languageCode = "ar"
title = "قالب شيكا"
theme = "Shika"

# Default content language
defaultContentLanguage = "ar"
defaultContentLanguageInSubdir = false

# Enable multiple languages
[languages]
  [languages.ar]
    languageName = "العربية"
    weight = 1
    title = "قالب شيكا"
    description = "قالب هوجو حديث وأنيق"
    contentDir = "content/ar"
    [languages.ar.params]
      languageDirection = "rtl"
  
  [languages.en]
    languageName = "English"
    weight = 2
    title = "Shika Theme"
    description = "A modern and elegant Hugo theme"
    contentDir = "content/en"
    [languages.en.params]
      languageDirection = "ltr"

# Site parameters
[params]
  author = "شيكا"
  description = "قالب هوجو حديث وأنيق"
  mainSections = ["posts", "tutorials"]
  
  # Social media
  github = "https://github.com/"
  twitter = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/"

# Arabic menu (default)
[menu]
  [[menu.main]]
    name = "الرئيسية"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "المقالات"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "الدروس"
    url = "/tutorials/"
    weight = 3
  [[menu.main]]
    name = "الوسوم"
    url = "/tags/"
    weight = 4

# English menu
[languages.en.menu]
  [[languages.en.menu.main]]
    name = "Home"
    url = "/en/"
    weight = 1
  [[languages.en.menu.main]]
    name = "Posts"
    url = "/en/posts/"
    weight = 2
  [[languages.en.menu.main]]
    name = "Tutorials"
    url = "/en/tutorials/"
    weight = 3
  [[languages.en.menu.main]]
    name = "Tags"
    url = "/en/tags/"
    weight = 4